CREATE TABLE IF NOT EXISTS swe_response_feedback (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source_id VARCHAR(64) NULL COMMENT '来源标识',
  feedback_user_name VARCHAR(128) NULL COMMENT '反馈人姓名',
  feedback_user_sap VARCHAR(64) NULL COMMENT '反馈人SAP',
  feedback_branch VARCHAR(128) NULL COMMENT '反馈人分行',
  feedback_sub_branch VARCHAR(128) NULL COMMENT '反馈人支行',
  feedback_position VARCHAR(128) NULL COMMENT '反馈人岗位',
  cron_task_name VARCHAR(255) NULL COMMENT '反馈定时任务名称',
  cron_task_id VARCHAR(128) NULL COMMENT '反馈定时任务ID',
  response_id VARCHAR(128) NULL COMMENT '相关回答ID',
  trace_id VARCHAR(36) NULL COMMENT '关联对话分析 traceId',
  chat_id VARCHAR(128) NULL COMMENT '聊天ID',
  session_id VARCHAR(256) NULL COMMENT '会话ID',
  feedback_options TEXT NULL COMMENT '快捷反馈选项（JSON 字符串）',
  feedback_content TEXT NOT NULL COMMENT '反馈内容',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_swe_response_feedback_response (response_id),
  KEY idx_swe_response_feedback_user (feedback_user_sap, created_at),
  KEY idx_swe_response_feedback_cron_task (cron_task_id, created_at),
  KEY idx_swe_response_feedback_chat (chat_id, created_at),
  KEY idx_swe_response_feedback_session (session_id, created_at),
  KEY idx_swe_response_feedback_source (source_id, created_at),
  KEY idx_swe_response_feedback_trace (trace_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回答反馈记录';
